version: '3'
services:

  dev-container:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: dev-container
    ports:
      - 3000:3000
      - 24678:24678 # vite (refs: https://qiita.com/kiyoshiro/items/9dcba9af830f7ca51323 )
      - 6006:6006 # storybook
    tty: true # コンテナの起動永続化
    volumes:
      - .:/usr/src/app
